spring.application.name=miapi
server.port=8085
springdoc.api-docs.path=/V3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


spring.datasource.url=jdbc:mysql://localhost:3306/miapi
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true    